version: "3.9"

services:
  db:
    image: timescale/timescaledb:latest-pg15
    container_name: gruppeeins_umwelt_db
    environment:
      POSTGRES_USER: gruppeeins
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: umwelt_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gruppeeins -d umwelt_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: umwelt_dashboard
    ports:
      - "8050:8050"
    environment:
      DB_USER: gruppeeins
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: umwelt_db
      SENSEBOX_ID: "67a661af4ef45d0008682744"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app

volumes:
  db_data:
